// =============================================================
//  POINTR — SCRIPT FILE
//  ⚙️  Form logic, progressive reveal, validation, submission.
//  ---------------------------------------------------------------
//  DO NOT edit this file to change content or labels.
//  Use content.js for all text changes.
//  Use config.js for behaviour toggles.
// =============================================================

const PROGRAM_LABELS = {
  qantas:   'Qantas Frequent Flyer',
  velocity: 'Virgin Velocity',
  flybuys:  'Coles Flybuys',
  everyday: 'Everyday Rewards',
  amex:     'Amex Membership Rewards',
  cba:      'CommBank Awards',
  anz:      'ANZ Rewards',
  nab:      'NAB Rewards',
  westpac:  'Westpac Altitude',
  nrma:     'NRMA Rewards',
  ihg:      'IHG One Rewards',
  marriott: 'Marriott Bonvoy',
  other:    'Other',
};

const FRUSTRATION_LABELS = {
  expiry:  'Points Expiring',
  value:   'Not knowing dollar value',
  logins:  'Too many apps / logins',
  redeem:  'Hard to transfer or redeem',
  other:   'Other',
};

// Wait for the DOM and content to be ready
document.addEventListener('DOMContentLoaded', () => {
  buildPage();
  initForm();
});


// =============================================================
//  PAGE BUILDER
//  Reads from CONTENT (content.js) and injects into index.html
// =============================================================

function buildPage() {
  const C = CONTENT;
  const F = CONTENT.form;

  // ── Meta ───────────────────────────────────────────────────
  document.title = C.meta.pageTitle;

  // ── Nav ────────────────────────────────────────────────────
  setHTML('nav-logo-text', buildLogo(C.nav.logoText));
  // setText('nav-pill-text', C.nav.pillText);
  // With this — renders the pill as a clickable link:
  setHTML('nav-pill-text', `
    <a href="${C.nav.pillLink}" 
       target="_blank" 
       rel="noopener noreferrer"
       style="text-decoration:none; color:inherit;">
      ${C.nav.pillText}
    </a>
  `);

  // ── Hero ───────────────────────────────────────────────────
  setText('eyebrow-text', C.hero.eyebrow);
  buildHeadline(C.hero.headline);
  setHTML('hero-sub-text', C.hero.subtext);
  buildStats(C.hero.stats);
  buildHeroChips();

  // ── Incentive ──────────────────────────────────────────────
  setText('inc-icon',  F.incentive ? CONTENT.incentive.icon  : '');
  setText('inc-title', CONTENT.incentive.title);
  setText('inc-desc',  CONTENT.incentive.desc);

  // ── Form ───────────────────────────────────────────────────
  setHTML('form-title', buildFormTitle(F.title, F.titleEm));
  setText('form-desc',  F.subtitle);

  // Field labels
  document.querySelector('[data-label="firstName"]').textContent = F.fields.firstName.label;
  document.querySelector('[data-label="email"]').textContent     = F.fields.email.label;
  document.querySelector('#firstName').placeholder = F.fields.firstName.placeholder;
  document.querySelector('#email').placeholder      = F.fields.email.email;

  // Programs
  setText('programs-label', F.programsLabel);
  buildPrograms(F.programs);

  // Goals
  setText('goals-label', F.goalsLabel);
  document.querySelector('#goals').placeholder = F.goalsPlaceholder;

  // Frustrations
  setText('frustrations-label', F.frustrationLabel);
  buildFrustrations(F.frustrations);
  document.querySelector('#frustration-other-text').placeholder = F.frustrationOtherPlaceholder;
  if (F.frustrationOtherRequired) {
    document.querySelector('#frustration-other-text').required = true;
  }

  // Price
  setText('price-label', F.priceLabel);
  buildPriceOptions(F.priceOptions);

  // CTA
  document.querySelector('#submit-btn').textContent = F.ctaText;
  setText('submit-note', F.submitNote);

  // Social proof
  buildProof(CONTENT.proof);

  // Success
  setText('suc-icon',    CONTENT.success.icon);
  setText('suc-title',   CONTENT.success.title);
  setHTML('suc-message', CONTENT.success.message);

  // Features
  buildFeatures(CONTENT.features);

  // Privacy
  setText('privacy-title', CONTENT.privacy.title);
  setHTML('privacy-text',  CONTENT.privacy.text);

  // Footer
  setHTML('footer-logo', buildLogo('Pointr'));
  setText('footer-note', CONTENT.footer.note);
}


// =============================================================
//  COMPONENT BUILDERS
//  Each function builds one section of the page.
// =============================================================

function buildLogo(text) {
  // Inserts a violet italic <em> for the "i" in "Pointr"
  return text.replace('i', '<em>i</em>');
}

function buildFormTitle(full, emWord) {
  return full.replace(emWord, `<em>${emWord}</em>`);
}

function buildHeadline(lines) {
  const el = document.getElementById('hero-headline');
  if (!el || !lines) return;
  // el.innerHTML = lines.map((line, i) => {
  //  if (i === 1) return `<span class="hl-violet">${line}</span>`;
  //  if (i === 2) return `<span class="hl-amber">${line}</span>`;
  //  return line;
  // }).join('<br>');
  //el.innerHTML = line.replace('points', 'po<em class="hl-violet">i</em>nts');
  el.innerHTML = lines.map((line, i) => {
    if (i === 2) return `<span class="hl-amber">${line}</span>`;
    return line;
  }).join('<br>');
}

function buildStats(stats) {
  const el = document.getElementById('stats-bar');
  if (!el) return;
  el.innerHTML = stats.map(s => `
    <div class="stat">
      <div class="stat-number${s.amber ? ' amber' : ''}">${s.number}</div>
      <div class="stat-label">${s.label}</div>
    </div>
  `).join('');
}

function buildHeroChips() {
  const el  = document.getElementById('hero-chips');
  const progs = CONTENT.form.programs.filter(p => p.value !== 'other').slice(0, 6);
  if (!el) return;
  el.innerHTML = progs.map(p => `
    <div class="prog-chip">
      <div class="dot" style="background:${p.dotColor}"></div>
      ${p.label}
    </div>
  `).join('');
}

function buildPrograms(programs) {
  const el = document.getElementById('programs-grid');
  if (!el) return;
  el.innerHTML = programs.map(p => `
    <label class="cb-item" id="cb-wrap-${p.value}">
      <input type="checkbox" name="programs" value="${p.value}"
             onchange="onProgramChange(this)">
      <span class="cb-text">
        <span class="dot" style="background:${p.dotColor}"></span>
        ${p.label}
      </span>
    </label>
  `).join('');
}

function buildFrustrations(frustrations) {
  const el = document.getElementById('frustrations-grid');
  if (!el) return;
  el.innerHTML = frustrations.map(f => `
    <div class="pill-opt" data-value="${f.value}" onclick="selFrust(this)">
      ${f.label}
    </div>
  `).join('');
}

function buildPriceOptions(options) {
  const el = document.getElementById('price-grid');
  if (!el) return;
  el.innerHTML = options.map(o => `
    <div class="price-opt" data-value="${o.value}" onclick="selPrice(this)">
      ${o.label}
      <span class="price-sub">${o.sub}</span>
    </div>
  `).join('');
}

function buildProof(items) {
  const el = document.getElementById('proof-row');
  if (!el) return;
  el.innerHTML = items.map(item => `
    <div class="proof-item">
      <div class="proof-dot"></div>
      ${item}
    </div>
  `).join('');
}

function buildFeatures(features) {
  const titleEl = document.getElementById('features-title');
  const subEl   = document.getElementById('features-sub');
  const gridEl  = document.getElementById('features-grid');
  if (!titleEl || !subEl || !gridEl) return;

  titleEl.innerHTML = features.title.replace(features.titleEm, `<em>${features.titleEm}</em>`);
  subEl.textContent = features.subtitle;

  gridEl.innerHTML = features.cards.map(c => `
    <div class="feat-card">
      <div class="feat-icon${c.amber ? ' amber' : ''}">${c.icon}</div>
      <div class="feat-name">${c.name}</div>
      <div class="feat-desc">${c.desc}</div>
    </div>
  `).join('');
}


// =============================================================
//  FORM LOGIC
// =============================================================

// Hidden values collected from interactive elements
const formState = {
  programs:    [],
  frustration: [],
  price:       null,
};

function initForm() {
  // Apply formMode from CONFIG
  const group2 = document.getElementById('form-group-2');
  if (!group2) return;

  if (CONFIG.formMode === 'all') {
    // Show everything immediately — for testing/review
    group2.classList.add('show-all');
  }
  // "progressive" mode is handled by onGroup1Change()
}


// ── PROGRESSIVE REVEAL ────────────────────────────────────────
// Called on every keyup/change in group 1 fields.
function onGroup1Change() {
  if (CONFIG.formMode === 'all') return; // skip in "all" mode

  const first = document.getElementById('firstName').value.trim();
  const email = document.getElementById('email').value.trim();
  const group2 = document.getElementById('form-group-2');
  if (!group2) return;

  const trigger = CONFIG.progressiveTrigger;
  let shouldReveal = false;

  if (trigger === 'name_and_email') {
    shouldReveal = first.length >= 2 && isValidEmail(email);
  } else if (trigger === 'email_only') {
    shouldReveal = isValidEmail(email);
  } else if (trigger === 'name_only') {
    shouldReveal = first.length >= 2;
  }

  if (shouldReveal) {
    group2.classList.add('revealed');
  } else {
    group2.classList.remove('revealed');
  }
}


// ── PROGRAM CHECKBOXES ────────────────────────────────────────
function onProgramChange(checkbox) {
  const wrap = document.getElementById(`cb-wrap-${checkbox.value}`);
  if (wrap) wrap.classList.toggle('checked', checkbox.checked);

  formState.programs = [...document.querySelectorAll('input[name="programs"]:checked')]
    .map(cb => cb.value);
}


// ── FRUSTRATION SELECTION ─────────────────────────────────────
function selFrust(el) {
  // Toggle this option on or off independently
  el.classList.toggle('sel');

  // Build array of all currently selected values
  formState.frustration = [...document.querySelectorAll('.pill-opt.sel')]
    .map(p => p.dataset.value);

  // Show/hide "Other" textarea based on whether "other" is selected
  const otherWrap = document.getElementById('frustration-other-wrap');
  if (otherWrap) {
    const otherSelected = formState.frustration.includes('other');
    otherWrap.classList.toggle('show', otherSelected);
  }
}


// ── PRICE SELECTION ───────────────────────────────────────────
function selPrice(el) {
  document.querySelectorAll('.price-opt').forEach(p => p.classList.remove('sel'));
  el.classList.add('sel');
  formState.price = el.dataset.value;
}


// =============================================================
//  VALIDATION
// =============================================================

function validateForm() {
  let valid = true;

  // First name
  const firstName = document.getElementById('firstName');
  const firstErr  = document.getElementById('error-firstName');
  if (!firstName.value.trim()) {
    firstName.classList.add('error');
    if (firstErr) firstErr.classList.add('show');
    valid = false;
  } else {
    firstName.classList.remove('error');
    if (firstErr) firstErr.classList.remove('show');
  }

  // Email
  const email    = document.getElementById('email');
  const emailErr = document.getElementById('error-email');
  if (!isValidEmail(email.value.trim())) {
    email.classList.add('error');
    if (emailErr) emailErr.classList.add('show');
    valid = false;
  } else {
    email.classList.remove('error');
    if (emailErr) emailErr.classList.remove('show');
  }

  // Frustration "Other" textarea (only if required in content.js)
  if (Array.isArray(formState.frustration) && 
    formState.frustration.includes('other') && 
    CONTENT.form.frustrationOtherRequired) {
    const otherText = document.getElementById('frustration-other-text');
    if (!otherText.value.trim()) {
      otherText.classList.add('error');
      valid = false;
    } else {
      otherText.classList.remove('error');
    }
  }

  return valid;
}

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}


// =============================================================
//  FORM SUBMISSION
// =============================================================

function handleSubmit() {
  if (!validateForm()) return;

  // Build submission object — this becomes your database row
  const submission = {
    timestamp:          new Date().toISOString(),
    firstName:          document.getElementById('firstName').value.trim(),
    email:              document.getElementById('email').value.trim(),
    programs:           formState.programs,
    goals:              document.getElementById('goals').value.trim(),
    frustration:        formState.frustration || [],
    frustrationOther:   document.getElementById('frustration-other-text')?.value.trim() || '',
    wouldPayPerMonth:   formState.price,
  };

  console.log('📋 Pointr submission:', submission);

  // ── Route to backend based on CONFIG.submitTo ──────────────
  if (CONFIG.submitTo === 'console') {
    // Dev mode — just log it
    console.log('ℹ️ submitTo is "console" in config.js. Change it to send data to a real backend.');
    showSuccess();

  } else if (CONFIG.submitTo === 'formspree') {
    fetch(CONFIG.formspree.endpoint, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body:    JSON.stringify(submission),
    })
    .then(r => r.ok ? showSuccess() : alert('Something went wrong. Please try again.'))
    .catch(() => alert('Something went wrong. Please try again.'));

  } else if (CONFIG.submitTo === 'airtable') {
  fetch(`https://api.airtable.com/v0/${CONFIG.airtable.baseId}/${encodeURIComponent(CONFIG.airtable.table)}`, {
    method:  'POST',
    headers: {
      'Authorization': `Bearer ${CONFIG.airtable.personalAccessToken}`,
      'Content-Type':  'application/json',
    },
    body: JSON.stringify({
      fields: {
        'First Name':   submission.firstName,
        'Email':        submission.email,
        'Programs':     submission.programs.map(p => PROGRAM_LABELS[p] || p),
        'Goals':        submission.goals,
        'Frustrations': Array.isArray(submission.frustration)
                          ? submission.frustration.map(f => FRUSTRATION_LABELS[f] || f)
                          : [],
        'Frustrations Details': submission.frustrationOther,
        'Would Pay':    submission.wouldPayPerMonth,
        'Timestamp':    submission.timestamp,
      }
    }),
  })
  .then(r => r.ok ? showSuccess() : alert('Something went wrong. Please try again.'))
  .catch(() => alert('Something went wrong. Please try again.'));
} else if (CONFIG.submitTo === 'mailchimp') {
    fetch(CONFIG.mailchimp.endpoint, {
      method: 'POST',
      body:   JSON.stringify(submission),
    })
    .then(() => showSuccess())
    .catch(() => alert('Something went wrong. Please try again.'));
  }
}

function showSuccess() {
  // Hide form content, show success state
  document.getElementById('form-inner').style.display = 'none';
  document.getElementById('success-state').classList.add('show');
  // Scroll form card into view on mobile
  document.querySelector('.form-card').scrollIntoView({ behavior: 'smooth', block: 'center' });
}


// =============================================================
//  UTILITY HELPERS
// =============================================================

function setText(id, text) {
  const el = document.getElementById(id);
  if (el) el.textContent = text;
}

function setHTML(id, html) {
  const el = document.getElementById(id);
  if (el) el.innerHTML = html;
}
